#:schema node_modules/wrangler/config-schema.json
name = "animedbsvelte"
compatibility_date = "2024-10-04"
pages_build_output_dir = ".svelte-kit/cloudflare"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/pages/functions/bindings/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/pages/functions/bindings/#secrets

[vars]
BASE_URL = "https://graphql.anilist.co"

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#kv-namespaces

[[kv_namespaces]]
binding = "API_CACHE"
id = "90e74fe0b9ab4d00b8c92bdd6daf5bd2"