#:schema node_modules/wrangler/config-schema.json
name = "animedbsvelte"
compatibility_date = "2024-10-04"
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
BASE_URL = "https://graphql.anilist.co"

[[kv_namespaces]]
binding = "API_CACHE"
id = "90e74fe0b9ab4d00b8c92bdd6daf5bd2"